package sdifstructures;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 516</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SdifTimePositionLS extends Structure {
	/** C type : SdifListT* */
	public sdifstructures.SdifListS.ByReference TimePosList;
	public SdifTimePositionLS() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("TimePosList");
	}
	/** @param TimePosList C type : SdifListT* */
	public SdifTimePositionLS(sdifstructures.SdifListS.ByReference TimePosList) {
		super();
		this.TimePosList = TimePosList;
	}
	public static class ByReference extends SdifTimePositionLS implements Structure.ByReference {
		
	};
	public static class ByValue extends SdifTimePositionLS implements Structure.ByValue {
		
	};
}
