package sdifstructures;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : line 290</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SdifListNS extends Structure {
	/** C type : SdifListNT* */
	public SdifListNS.ByReference Next;
	/** C type : void* */
	public Pointer Data;
	public SdifListNS() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Next", "Data");
	}
	/**
	 * @param Next C type : SdifListNT*<br>
	 * @param Data C type : void*
	 */
	public SdifListNS(SdifListNS.ByReference Next, Pointer Data) {
		super();
		this.Next = Next;
		this.Data = Data;
	}
	public static class ByReference extends SdifListNS implements Structure.ByReference {
		
	};
	public static class ByValue extends SdifListNS implements Structure.ByValue {
		
	};
}
