package sdifstructures;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : line 418</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SdifFrameTypeS extends Structure {
	/** C type : SdifSignature */
	public int Signature;
	/** C type : SdifFrameTypeT* */
	public SdifFrameTypeS.ByReference FrameTypePre;
	/** C type : SdifHashTableT* */
	public sdifstructures.SdifHashTableS.ByReference ComponentUseHT;
	/** C type : SdifUInt4 */
	public int NbComponentUse;
	/** C type : SdifUInt4 */
	public int NbComponent;
	/** C type : SdifModifModeET */
	public int ModifMode;
	public SdifFrameTypeS() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Signature", "FrameTypePre", "ComponentUseHT", "NbComponentUse", "NbComponent", "ModifMode");
	}
	/**
	 * @param Signature C type : SdifSignature<br>
	 * @param FrameTypePre C type : SdifFrameTypeT*<br>
	 * @param ComponentUseHT C type : SdifHashTableT*<br>
	 * @param NbComponentUse C type : SdifUInt4<br>
	 * @param NbComponent C type : SdifUInt4<br>
	 * @param ModifMode C type : SdifModifModeET
	 */
	public SdifFrameTypeS(int Signature, SdifFrameTypeS.ByReference FrameTypePre, sdifstructures.SdifHashTableS.ByReference ComponentUseHT, int NbComponentUse, int NbComponent, int ModifMode) {
		super();
		this.Signature = Signature;
		this.FrameTypePre = FrameTypePre;
		this.ComponentUseHT = ComponentUseHT;
		this.NbComponentUse = NbComponentUse;
		this.NbComponent = NbComponent;
		this.ModifMode = ModifMode;
	}
	public static class ByReference extends SdifFrameTypeS implements Structure.ByReference {
		
	};
	public static class ByValue extends SdifFrameTypeS implements Structure.ByValue {
		
	};
}
