package sdifstructures;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SdifSelectIntMaskS extends Structure {
	/**
	 * number of ints selected<br>
	 * C type : SdifUInt4
	 */
	public int num;
	/**
	 * max given int, #elems in mask<br>
	 * C type : SdifUInt4
	 */
	public int max;
	/**
	 * selection bit mask<br>
	 * C type : int*
	 */
	public IntByReference mask;
	/** are elems > max included? */
	public int openend;
	public SdifSelectIntMaskS() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("num", "max", "mask", "openend");
	}
	/**
	 * @param num number of ints selected<br>
	 * C type : SdifUInt4<br>
	 * @param max max given int, #elems in mask<br>
	 * C type : SdifUInt4<br>
	 * @param mask selection bit mask<br>
	 * C type : int*<br>
	 * @param openend are elems > max included?
	 */
	public SdifSelectIntMaskS(int num, int max, IntByReference mask, int openend) {
		super();
		this.num = num;
		this.max = max;
		this.mask = mask;
		this.openend = openend;
	}
	public static class ByReference extends SdifSelectIntMaskS implements Structure.ByReference {
		
	};
	public static class ByValue extends SdifSelectIntMaskS implements Structure.ByValue {
		
	};
}
