package sdifstructures;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Structure;
/**
 * <i>native declaration : line 391</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SdifMatrixTypeS extends Structure {
	/** C type : SdifSignature */
	public int Signature;
	/** C type : SdifMatrixTypeT* */
	public SdifMatrixTypeS.ByReference MatrixTypePre;
	/**
	 * List of columns added by user: <br>
	 * SdifMatrixTypeInsertTailColumn(MatrixTypeT *)<br>
	 * C type : SdifListT*
	 */
	public sdifstructures.SdifListS.ByReference ColumnUserList;
	/**
	 * Number of columns created by user:<br>
	 * SdifMatrixTypeInsertTailColumn(MatrixTypeT *)<br>
	 * C type : SdifUInt4
	 */
	public int NbColumnDef;
	/** C type : SdifModifModeET */
	public int ModifMode;
	public SdifMatrixTypeS() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Signature", "MatrixTypePre", "ColumnUserList", "NbColumnDef", "ModifMode");
	}
	/**
	 * @param Signature C type : SdifSignature<br>
	 * @param MatrixTypePre C type : SdifMatrixTypeT*<br>
	 * @param ColumnUserList List of columns added by user: <br>
	 * SdifMatrixTypeInsertTailColumn(MatrixTypeT *)<br>
	 * C type : SdifListT*<br>
	 * @param NbColumnDef Number of columns created by user:<br>
	 * SdifMatrixTypeInsertTailColumn(MatrixTypeT *)<br>
	 * C type : SdifUInt4<br>
	 * @param ModifMode C type : SdifModifModeET
	 */
	public SdifMatrixTypeS(int Signature, SdifMatrixTypeS.ByReference MatrixTypePre, sdifstructures.SdifListS.ByReference ColumnUserList, int NbColumnDef, int ModifMode) {
		super();
		this.Signature = Signature;
		this.MatrixTypePre = MatrixTypePre;
		this.ColumnUserList = ColumnUserList;
		this.NbColumnDef = NbColumnDef;
		this.ModifMode = ModifMode;
	}
	public static class ByReference extends SdifMatrixTypeS implements Structure.ByReference {
		
	};
	public static class ByValue extends SdifMatrixTypeS implements Structure.ByValue {
		
	};
}
