package sdifstructures;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SdifSelectValueS extends Union {
	/** C type : SdifUInt4 */
	public int integer;
	public double real;
	/** C type : char* */
	public Pointer string;
	/** C type : SdifSignature */
	public int signature;
	public SdifSelectValueS() {
		super();
	}
	/** @param integer_or_signature C type : SdifUInt4, or C type : SdifSignature */
	public SdifSelectValueS(int integer_or_signature) {
		super();
		this.signature = this.integer = integer_or_signature;
		setType(Integer.TYPE);
	}
	public SdifSelectValueS(double real) {
		super();
		this.real = real;
		setType(Double.TYPE);
	}
	/** @param string C type : char* */
	public SdifSelectValueS(Pointer string) {
		super();
		this.string = string;
		setType(Pointer.class);
	}
	public static class ByReference extends SdifSelectValueS implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends SdifSelectValueS implements com.sun.jna.Structure.ByValue {
		
	};
}
