package sdifstructures;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 328</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SdifNameValueS extends Structure {
	/** C type : char* */
	public Pointer Name;
	/** C type : char* */
	public Pointer Value;
	public SdifNameValueS() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Name", "Value");
	}
	/**
	 * @param Name C type : char*<br>
	 * @param Value C type : char*
	 */
	public SdifNameValueS(Pointer Name, Pointer Value) {
		super();
		this.Name = Name;
		this.Value = Value;
	}
	public static class ByReference extends SdifNameValueS implements Structure.ByReference {
		
	};
	public static class ByValue extends SdifNameValueS implements Structure.ByValue {
		
	};
}
